// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBJJoVRyDe8ECPnAQB3JpzBPytkeZPGt6w',
    appId: '1:605736509175:web:8f07ee6498127cf8c23df2',
    messagingSenderId: '605736509175',
    projectId: 'bonepay-demo',
    authDomain: 'bonepay-demo.firebaseapp.com',
    storageBucket: 'bonepay-demo.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDqymmw5O2WuaDiUPTFs6Y9EMF5dYek1AM',
    appId: '1:605736509175:android:52e04b5cbdbd0f6fc23df2',
    messagingSenderId: '605736509175',
    projectId: 'bonepay-demo',
    storageBucket: 'bonepay-demo.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCn2NLHDVLtG8I5GBvHinH0wPOUJSadE-w',
    appId: '1:605736509175:ios:56f088497edf3ab4c23df2',
    messagingSenderId: '605736509175',
    projectId: 'bonepay-demo',
    storageBucket: 'bonepay-demo.firebasestorage.app',
    iosBundleId: 'com.example.bonepayDemo',
  );
}
